#!/bin/env perl
use 5.12.0;
use warnings;

use lib 'lib';

use Getopt::Long::Descriptive;
use Roland::Hub;

my ($opt, $usage) = describe_options(
  '%c %o <table>',
  [ 'manual|m', 'enter die rolls manually' ],
  [ 'mode=s',   'table mode', { default => 'table' } ],
);

my $hub = Roland::Hub->new({ manual => $opt->manual });

if ($opt->mode eq 'table') {
  say "rolled on $ARGV[0]";
  say $hub->resolve_table($ARGV[0])->as_text;
} elsif ($opt->mode eq 'monster') {
  say $hub->resolve_monster($ARGV[0])->as_text;
} else {
  die "unknown mode" unless $opt->mode eq 'table';
}
