#!/bin/env perl
use 5.12.0;
use warnings;

use lib 'lib';

use Getopt::Long::Descriptive;
use Roland::Hub;

my ($opt, $usage) = describe_options(
  '%c %o <table>',
  [ 'manual|m', 'enter die rolls manually' ],
);

my $hub = Roland::Hub->new({ manual => $opt->manual });

say "rolling on on $ARGV[0]";
say $hub->resolve_table($ARGV[0])->as_text;
